name: Test and deploy

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

  static-analysis:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Static Analysis
        env:
          MOT_API_KEY: ${{ secrets.MOT_API_KEY }}
        run: ./gradlew detekt

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: detekt
          path: app/build/reports/detekt/

  unit_tests:
    needs: [ static-analysis ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test

      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: unit-test-reports
          path: '**/build/reports/tests/testDebugUnitTest'
#
#  android_tests:
#    needs: [ static-analysis ]
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set Up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Instrumentation Tests
#        env:
#          MOT_API_KEY: ${{ secrets.MOT_API_KEY }}
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest

  build:
#    needs: [ unit_tests, android_tests ]
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release APK
        env:
          MOT_API_KEY: ${{ secrets.MOT_API_KEY }}
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt
